# Generated by Django 5.1 on 2024-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilots',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
