# Generated by Django 5.1 on 2024-08-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_farms_alter_usuarios_table_talhao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talhao',
            name='id',
        ),
        migrations.AlterField(
            model_name='talhao',
            name='id_talhao',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
