# Generated by Django 5.1 on 2024-08-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_talhao_id_alter_talhao_id_talhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talhao',
            name='cultura',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='technician',
            field=models.TextField(null=True),
        ),
    ]
