# Generated by Django 5.1 on 2024-08-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_talhao_cultura_alter_talhao_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talhao',
            old_name='id_farm',
            new_name='farm_id',
        ),
    ]
