# Generated by Django 5.1 on 2024-08-22 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_id_farm_talhao_farm_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talhao',
            old_name='farm_id',
            new_name='farm',
        ),
    ]
