# Generated by Django 5.1 on 2024-08-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_talhao_unique_field1_field2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='talhao',
            name='unique_field1_field2',
        ),
    ]
