# Generated by Django 5.1 on 2024-09-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pilots',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='talhao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
    ]
