# Generated by Django 5.1 on 2024-09-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_farms_options_alter_pilots_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talhao',
            name='cultura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='technician',
            field=models.TextField(blank=True, null=True),
        ),
    ]
