# Generated by Django 5.1 on 2024-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_talhao_cultura_alter_talhao_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grupo_Produto',
            field=models.CharField(choices=[('acaricida', 'Acaricida'), ('agente biológico de controle', 'Agente biológico de controle'), ('ativador de planta', 'Ativador de planta'), ('bactericida', 'Bactericida'), ('cupinicida', 'Cupinicida'), ('feromônio', 'Feromônio'), ('fertilizante', 'Fertilizante'), ('formicida', 'Formicida'), ('fungicida', 'Fungicida'), ('herbicida', 'Herbicida'), ('inseticida', 'Inseticida'), ('nematicida', 'Nematicida'), ('regulador de crescimento', 'Regulador de crescimento')], default='acaricida', max_length=50),
        ),
    ]
