# Generated by Django 5.1 on 2024-09-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_grupo_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='grupo_Produto',
            new_name='grupo_produto',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nome_Comercial',
            new_name='nome_comercial',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='principio_Ativo',
            new_name='principio_ativo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='taxa_Aplicacao',
            new_name='taxa_aplicacao',
        ),
        migrations.RemoveField(
            model_name='product',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='product',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
