# Generated by Django 5.1 on 2024-09-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_grupo_produto_product_grupo_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='id_farm',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
