# Generated by Django 5.1 on 2024-09-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_usuarios_usuario_alter_product_grupo_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.TextField()),
                ('manufacturer', models.CharField(choices=[('', 'Escolha o fabricante'), ('DJI', 'DJI')], max_length=50)),
                ('capacity', models.FloatField()),
            ],
            options={
                'db_table': 'aeronave',
            },
        ),
        migrations.RenameModel(
            old_name='Pilots',
            new_name='Pilot',
        ),
        migrations.AlterField(
            model_name='product',
            name='grupo_produto',
            field=models.CharField(choices=[('', 'Escolha o Grupo do Produto'), ('Acaricida', 'Acaricida'), ('Agente biológico de controle', 'Agente biológico de controle'), ('Ativador de planta', 'Ativador de planta'), ('Bactericida', 'Bactericida'), ('Cupinicida', 'Cupinicida'), ('Feromônio', 'Feromônio'), ('Fertilizante', 'Fertilizante'), ('Formicida', 'Formicida'), ('Fungicida', 'Fungicida'), ('Herbicida', 'Herbicida'), ('Inseticida', 'Inseticida'), ('Nematicida', 'Nematicida'), ('Regulador de crescimento', 'Regulador de crescimento')], max_length=50),
        ),
    ]
