# Generated by Django 5.1 on 2024-09-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_farms_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talhao',
            name='cultura',
        ),
    ]
