# Generated by Django 5.1 on 2024-09-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_talhao_cultura'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pilot',
            table='pilot',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='user',
        ),
    ]
