# Generated by Django 5.1 on 2024-09-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_farm_table_guia_aplicacao_supervisor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guia_aplicacao_supervisor',
            table='guia_aplicacao_supervisor',
        ),
    ]
