# Generated by Django 5.1 on 2024-09-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_guia_aplicacao_supervisor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_aplicacao_supervisor',
            name='talhao',
            field=models.CharField(default='', max_length=50),
        ),
    ]
