# Generated by Django 5.1 on 2024-09-23 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_activity_pilot_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_aplicacao_supervisor',
            name='id_piloto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.pilot'),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
