# Generated by Django 5.1 on 2024-09-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_guia_aplicacao_supervisor_id_piloto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia_aplicacao_piloto',
            fields=[
                ('id_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.guia_aplicacao_supervisor')),
                ('data_realizacao', models.DateTimeField()),
                ('bicos', models.IntegerField()),
                ('direcao_vento', models.CharField(max_length=50)),
                ('vazao', models.FloatField()),
                ('altura_voo', models.FloatField()),
                ('umidade', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('rajada_vento', models.FloatField()),
                ('realizado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'guia_aplicacao_piloto',
            },
        ),
    ]
