# Generated by Django 5.1 on 2024-09-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_guia_aplicacao_piloto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='id_aplicacao',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_supervisor'),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='cultura',
            field=models.CharField(choices=[('', 'Selecione a cultura'), ('Algodão', 'Algodão'), ('Cana-de-açucar', 'Cana-de-açucar'), ('Milho', 'Milho'), ('Pasto', 'Pasto'), ('Soja', 'Soja')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='talhao',
            field=models.TextField(default='', max_length=50),
        ),
    ]
