# Generated by Django 5.1 on 2024-09-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_guia_aplicacao_piloto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='id_aplicacao',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.guia_aplicacao_supervisor'),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='talhao',
            field=models.TextField(default=''),
        ),
    ]
