# Generated by Django 5.1 on 2024-10-24 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_guia_aplicacao_supervisor_id_responsavel_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
