# Generated by Django 5.1 on 2024-10-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_guia_aplicacao_supervisor_id_responsavel_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='id_responsavel_global',
            field=models.ForeignKey(blank=True, db_column='id_responsavel_global', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.authuser'),
        ),
        migrations.CreateModel(
            name='Foto_cond_atmosferica',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.BinaryField()),
                ('id_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_piloto')),
            ],
            options={
                'db_table': 'foto_cond_atmosferica',
            },
        ),
        migrations.CreateModel(
            name='Foto_panoramica',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.BinaryField()),
                ('id_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_piloto')),
            ],
            options={
                'db_table': 'foto_panoramica',
            },
        ),
        migrations.CreateModel(
            name='Foto_produto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.BinaryField()),
                ('id_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_piloto')),
            ],
            options={
                'db_table': 'foto_produto',
            },
        ),
        migrations.CreateModel(
            name='Foto_telemetria',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.BinaryField()),
                ('id_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_piloto')),
            ],
            options={
                'db_table': 'foto_telemetria',
            },
        ),
        migrations.CreateModel(
            name='Foto_trajeto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.BinaryField()),
                ('id_aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_piloto')),
            ],
            options={
                'db_table': 'foto_trajeto',
            },
        ),
    ]
