# Generated by Django 5.1 on 2024-10-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_guia_aplicacao_supervisor_id_responsavel_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_cond_atmosferica',
            name='foto',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='foto_panoramica',
            name='foto',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='foto_produto',
            name='foto',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='foto_telemetria',
            name='foto',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='foto_trajeto',
            name='foto',
            field=models.BinaryField(editable=True),
        ),
    ]
