# Generated by Django 5.1 on 2024-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_foto_cond_atmosferica_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_aplicacao_piloto',
            name='observacao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='foto_cond_atmosferica',
            name='foto',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='altura_voo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='bicos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='direcao_vento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='rajada_vento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='realizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='umidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='vazao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
