# Generated by Django 5.1 on 2024-11-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_guia_aplicacao_supervisor_id_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_aplicacao_supervisor',
            name='id_receita',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.receita'),
        ),
    ]
