# Generated by Django 5.1.3 on 2024-11-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_guia_aplicacao_supervisor_id_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='id_guia_sup',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.guia_aplicacao_supervisor'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='guia_aplicacao_supervisor',
            name='id_receita',
        ),
        migrations.AddField(
            model_name='guia_aplicacao_supervisor',
            name='id_receita',
            field=models.ManyToManyField(through='api.Receita', to='api.product'),
        ),
    ]
