# Generated by Django 5.1.3 on 2025-01-30 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_receita_id_guia_sup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='id_fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.farm'),
        ),
    ]
