# Generated by Django 5.1.3 on 2025-02-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_guia_aplicacao_supervisor_id_fazenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia_aplicacao_supervisor',
            name='id_piloto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.pilot'),
        ),
    ]
