# Generated by Django 5.1.3 on 2025-02-07 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_guia_aplicacao_supervisor_id_piloto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto_cond_atmosferica',
            name='id_aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.guia_aplicacao_piloto'),
        ),
        migrations.AlterField(
            model_name='foto_panoramica',
            name='id_aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.guia_aplicacao_piloto'),
        ),
        migrations.AlterField(
            model_name='foto_produto',
            name='id_aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.guia_aplicacao_piloto'),
        ),
        migrations.AlterField(
            model_name='foto_trajeto',
            name='id_aplicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.guia_aplicacao_piloto'),
        ),
        migrations.AlterField(
            model_name='guia_aplicacao_piloto',
            name='id_aplicacao',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='api.guia_aplicacao_supervisor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id_guia_sup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.guia_aplicacao_supervisor'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
        migrations.AlterField(
            model_name='talhao',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='api.farm'),
        ),
    ]
