# Generated by Django 5.1.3 on 2025-02-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_foto_cond_atmosferica_id_aplicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_aplicacao_supervisor',
            name='cod_solicitacao_voo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
