
services:
  web:
    build: ./
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - ${APP_EXPOSE_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      - db-dev
  db-dev:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data-dev/
    env_file:
      - ./.env
    ports:
      - "5433:5432"  # Mapping container port 5432 to local port 5433

volumes:
  postgres_data: