services:

  db:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data-prod/
    env_file:
      - ./.env.prod
  web:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    # command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - web
volumes:
  postgres_data: